CREATE TABLE public.af_fixtures (
  id bigint NOT NULL,
  league_id bigint,
  season integer,
  date timestamp with time zone NOT NULL,
  status_short text,
  status_long text,
  minute integer,
  referee text,
  venue text,
  home_team_id bigint,
  away_team_id bigint,
  goals_home integer,
  goals_away integer,
  score_ht_home integer,
  score_ht_away integer,
  score_ft_home integer,
  score_ft_away integer,
  score_et_home integer,
  score_et_away integer,
  score_p_home integer,
  score_p_away integer,
  last_sync_at timestamp with time zone,
  red_home integer,
  red_away integer
);
