CREATE TABLE public.matches (
  id bigint DEFAULT nextval('matches_id_seq'::regclass) NOT NULL,
  start_time timestamp with time zone NOT NULL,
  lock_time timestamp with time zone NOT NULL,
  league text NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  dur_min integer DEFAULT 110,
  bonus_id bigint,
  created_at timestamp with time zone DEFAULT now(),
  af_fixture_id bigint,
  status text,
  score_home integer,
  score_away integer,
  live_minute integer,
  last_sync_at timestamp with time zone,
  red_home integer,
  red_away integer,
  result_1x2 text,
  btts boolean,
  over_25 boolean,
  final_home integer,
  final_away integer
);
