ALTER TABLE public.af_fixtures ADD CONSTRAINT af_fixtures_away_team_id_fkey FOREIGN KEY FOREIGN KEY (away_team_id) REFERENCES af_teams(id);
ALTER TABLE public.af_fixtures ADD CONSTRAINT af_fixtures_home_team_id_fkey FOREIGN KEY FOREIGN KEY (home_team_id) REFERENCES af_teams(id);
ALTER TABLE public.af_fixtures ADD CONSTRAINT af_fixtures_league_id_fkey FOREIGN KEY FOREIGN KEY (league_id) REFERENCES af_leagues(id) ON DELETE CASCADE;
ALTER TABLE public.af_fixtures ADD CONSTRAINT af_fixtures_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.af_leagues ADD CONSTRAINT af_leagues_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.af_teams ADD CONSTRAINT af_teams_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.app_config ADD CONSTRAINT app_config_pkey PRIMARY KEY PRIMARY KEY (key);
ALTER TABLE public.email_outbox ADD CONSTRAINT email_outbox_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.email_outbox ADD CONSTRAINT email_outbox_status_check CHECK ((status = ANY (ARRAY['PENDING'::text, 'SENT'::text, 'FAILED'::text])));
ALTER TABLE public.match_results ADD CONSTRAINT match_results_match_id_fkey FOREIGN KEY FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.match_results ADD CONSTRAINT match_results_pkey PRIMARY KEY PRIMARY KEY (match_id);
ALTER TABLE public.matches ADD CONSTRAINT matches_af_fixture_id_key UNIQUE UNIQUE (af_fixture_id);
ALTER TABLE public.matches ADD CONSTRAINT matches_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.matches ADD CONSTRAINT matches_result_1x2_check CHECK ((result_1x2 = ANY (ARRAY['HOME'::text, 'DRAW'::text, 'AWAY'::text])));
ALTER TABLE public.onboarding_submissions ADD CONSTRAINT onboarding_submissions_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.onboarding_submissions ADD CONSTRAINT onboarding_submissions_user_id_fkey FOREIGN KEY FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY PRIMARY KEY (user_id);
ALTER TABLE public.profiles ADD CONSTRAINT profiles_user_id_fkey FOREIGN KEY FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.seed_audit ADD CONSTRAINT seed_audit_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.ticket_answers ADD CONSTRAINT ticket_answers_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.ticket_answers ADD CONSTRAINT ticket_answers_q_key_check CHECK ((q_key = ANY (ARRAY['s1'::text, 's2'::text, 's3'::text, 's4'::text, 's5'::text])));
ALTER TABLE public.ticket_answers ADD CONSTRAINT ticket_answers_ticket_id_fkey FOREIGN KEY FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_scores ADD CONSTRAINT ticket_scores_match_id_fkey FOREIGN KEY FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_scores ADD CONSTRAINT ticket_scores_pkey PRIMARY KEY PRIMARY KEY (ticket_id);
ALTER TABLE public.ticket_scores ADD CONSTRAINT ticket_scores_ticket_id_fkey FOREIGN KEY FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_scores_live ADD CONSTRAINT ticket_scores_live_match_id_fkey FOREIGN KEY FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.ticket_scores_live ADD CONSTRAINT ticket_scores_live_pkey PRIMARY KEY PRIMARY KEY (ticket_id);
ALTER TABLE public.ticket_scores_live ADD CONSTRAINT ticket_scores_live_ticket_id_fkey FOREIGN KEY FOREIGN KEY (ticket_id) REFERENCES tickets(id) ON DELETE CASCADE;
ALTER TABLE public.tickets ADD CONSTRAINT tickets_match_id_fkey FOREIGN KEY FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE CASCADE;
ALTER TABLE public.tickets ADD CONSTRAINT tickets_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.tickets ADD CONSTRAINT tickets_status_check CHECK ((status = ANY (ARRAY['SUBMITTED'::text, 'LOCKED'::text, 'SCORED'::text])));
ALTER TABLE public.tickets ADD CONSTRAINT tickets_user_id_fkey FOREIGN KEY FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE public.users ADD CONSTRAINT users_pkey PRIMARY KEY PRIMARY KEY (id);
ALTER TABLE public.users ADD CONSTRAINT users_user_id_fkey FOREIGN KEY FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
