CREATE UNIQUE INDEX af_fixtures_pkey ON public.af_fixtures USING btree (id)
CREATE UNIQUE INDEX af_leagues_pkey ON public.af_leagues USING btree (id)
CREATE UNIQUE INDEX af_teams_pkey ON public.af_teams USING btree (id)
CREATE UNIQUE INDEX app_config_pkey ON public.app_config USING btree (key)
CREATE UNIQUE INDEX email_outbox_pkey ON public.email_outbox USING btree (id)
CREATE UNIQUE INDEX match_results_pkey ON public.match_results USING btree (match_id)
CREATE INDEX idx_matches_lock_time ON public.matches USING btree (lock_time)
CREATE INDEX idx_matches_start_time ON public.matches USING btree (start_time)
CREATE INDEX idx_matches_status ON public.matches USING btree (status)
CREATE UNIQUE INDEX matches_af_fixture_id_key ON public.matches USING btree (af_fixture_id)
CREATE UNIQUE INDEX matches_pkey ON public.matches USING btree (id)
CREATE UNIQUE INDEX onboarding_submissions_pkey ON public.onboarding_submissions USING btree (id)
CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (user_id)
CREATE UNIQUE INDEX uq_profiles_username_ci ON public.profiles USING btree (lower(username)) WHERE (username IS NOT NULL)
CREATE INDEX idx_seed_audit_date ON public.seed_audit USING btree (target_date)
CREATE UNIQUE INDEX seed_audit_pkey ON public.seed_audit USING btree (id)
CREATE INDEX idx_answers_ticket ON public.ticket_answers USING btree (ticket_id)
CREATE UNIQUE INDEX ticket_answers_pkey ON public.ticket_answers USING btree (id)
CREATE UNIQUE INDEX uq_answers_ticket_key ON public.ticket_answers USING btree (ticket_id, q_key)
CREATE UNIQUE INDEX ticket_scores_pkey ON public.ticket_scores USING btree (ticket_id)
CREATE INDEX idx_tsl_match ON public.ticket_scores_live USING btree (match_id)
CREATE UNIQUE INDEX ticket_scores_live_pkey ON public.ticket_scores_live USING btree (ticket_id)
CREATE INDEX idx_tickets_match ON public.tickets USING btree (match_id)
CREATE INDEX idx_tickets_user ON public.tickets USING btree (user_id)
CREATE UNIQUE INDEX tickets_pkey ON public.tickets USING btree (id)
CREATE INDEX idx_users_user_id ON public.users USING btree (user_id)
CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id)
