CREATE INDEX idx_matches_lock_time ON public.matches USING btree (lock_time);
CREATE INDEX idx_matches_start_time ON public.matches USING btree (start_time);
CREATE INDEX idx_matches_status ON public.matches USING btree (status);
CREATE UNIQUE INDEX uq_profiles_username_ci ON public.profiles USING btree (lower(username)) WHERE (username IS NOT NULL);
CREATE INDEX idx_seed_audit_date ON public.seed_audit USING btree (target_date);
CREATE INDEX idx_answers_ticket ON public.ticket_answers USING btree (ticket_id);
CREATE UNIQUE INDEX uq_answers_ticket_key ON public.ticket_answers USING btree (ticket_id, q_key);
CREATE INDEX idx_tsl_match ON public.ticket_scores_live USING btree (match_id);
CREATE INDEX idx_tickets_match ON public.tickets USING btree (match_id);
CREATE INDEX idx_tickets_user ON public.tickets USING btree (user_id);
CREATE INDEX idx_users_user_id ON public.users USING btree (user_id);
