name: Apply Supabase migrations

on:
  push:
    branches: [ main ]
    paths:
      - "supabase/migrations/**/*.sql"
  workflow_dispatch: {}

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: supabase-migrations
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          mkdir -p supabase
          supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      - name: Apply migrations (db push)
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: |
          supabase db push
